# Generated by Django 3.2.19 on 2023-07-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_pretttnum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PretttNum',
            new_name='PrettyNum',
        ),
    ]
